name: release_docker

on:
  workflow_dispatch:
  push:
    branches: ["main","release"]
    paths:
      - 'node-proxy/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'node-proxy/**'

jobs:
  release_docker:
    name: Release Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd node-proxy
          npm install && npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build 和 push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: zl0104/alist-encrypt:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
